boards/red-pitaya/base_system.tcl
boards/red-pitaya/config/ports.tcl
scripts/bram.tcl
scripts/project.tcl

Base system

---

boards/red-pitaya/base_system.tcl
cores/redp_adc_dac_v1_0/redp_adc_dac.v

Remove clock converter

---

Makefile
boards/red-pitaya/base_system.tcl
boards/red-pitaya/config/clocks.xdc
cores/redp_adc_dac_v1_0/redp_adc_dac.v
cores/redp_adc_v1_0/COPYING
cores/redp_adc_v1_0/core_config.tcl
cores/redp_adc_v1_0/redp_adc.v
cores/redp_dac_v1_0/COPYING
cores/redp_dac_v1_0/core_config.tcl
cores/redp_dac_v1_0/redp_dac.v
projects/base_system/block_design.tcl

Redp nomenclature

---

scripts/ubuntu.sh

Fix ubuntu

---

Makefile

Fixes problems when firewall does not allow ssh protocol.

clone using https instead of ssh

---

devices/dac/dac.hpp
projects/spectrum/block_design.tcl
projects/spectrum/spectrum/spectrum.cpp
projects/spectrum/spectrum/spectrum.hpp

Stream peak

---

README.md
boards/red-pitaya/patches/linux-xlnx-xilinx-v2016.1.patch
scripts/ubuntu.sh

* Stop nginx running on port 80 :
`systemctl stop nginx.service`
* Run  [Hypriot test docker image](http://blog.hypriot.com/getting-started-with-docker-on-your-arm-device/) :
`docker run -d -p 80:80 hypriot/rpi-busybox-httpd`

Docker Hello World working

---

boards/red-pitaya/base_system.tcl
lib/redp_adc_dac.tcl

use procedure to add redp_adc_dac

---

drivers/device_memory/device_memory.cpp
drivers/device_memory/device_memory.hpp
drivers/laser/laser.cpp
drivers/laser/laser.hpp
drivers/lib/dev_mem.cpp
drivers/lib/dev_mem.hpp
drivers/oscillo/oscillo.cpp
drivers/oscillo/oscillo.hpp
drivers/pid/pid.cpp
drivers/pid/pid.hpp
drivers/spectrum/spectrum.cpp
drivers/spectrum/spectrum.hpp
drivers/speed_test/speed_test.cpp
drivers/speed_test/speed_test.hpp
drivers/xadc/xadc.cpp
drivers/xadc/xadc.hpp

For instance :
```cpp
Klib::WriteReg32(dev_mem.GetBaseAddr(config_map) + PWM3_OFF, voltage);
```
is replaced with 
```cpp
dvm.write32(config_map, PWM3_OFF, voltage);
```

Improve devmem

---

boards/red-pitaya/base_system.tcl
fpga/tcl/utilities.tcl
projects/base/block_design.tcl
projects/oscillo/oscillo.tcl
projects/pid/block_design.tcl
projects/spectrum/spectrum.tcl

```tcl
proc cfg_pin {name} {
return $::config_name/Out[set config::${name}_offset]
}
proc sts_pin {name} {
return $::status_name/In[set config::${name}_offset]
}
```

add cfg_pin and sts_pin procedures

---

fpga/tcl/dac_controller.tcl
projects/base/block_design.tcl

* replace `add_dac_controller` with add `add_dual_dac_controller`
* hotfix : connect BRAM clock inside `add_dual_dac_controller`

add_dual_dac_controller procedure

---

fpga/tcl/adc_controller.tcl
fpga/tcl/bram_recorder.tcl
projects/oscillo/oscillo.tcl
projects/spectrum/spectrum.tcl

Add a simple module to record adc data on BRAM

Bram recorder

---

fpga/tcl/bram_recorder.tcl
fpga/tcl/pid_controller.tcl
fpga/tcl/redp_adc_dac.tcl
fpga/tcl/utilities.tcl
projects/base/block_design.tcl
projects/oscillo/oscillo.tcl
projects/spectrum/spectrum.tcl

Add `conect_cell` and `set_cell_props` procedures

Connect cell

---

fpga/tcl/bram_recorder.tcl

connect addr in bram recorder

---

drivers/at93c46d/at93c46d.hpp

Available in C++14 (http://en.cppreference.com/w/cpp/chrono/operator%22%22us)

Try std::literals::chrono_literals

---

README.md
drivers/spectrum/__init__.py
scripts/make.py

Clean python

---

drivers/device_memory/device_memory.hpp
drivers/lib/dev_mem.hpp
drivers/lib/fifo_reader.hpp
drivers/lib/memory_map.hpp
drivers/lib/spi_dev.cpp
drivers/lib/spi_dev.hpp
drivers/spi/__init__.py
drivers/spi/spi.hpp
projects/oscillo/drivers.yml
tests/spi.py

First version of the SpiDev driver. For now only write.

Spi driver

---

fpga/tcl/utilities.tcl
projects/address_module/address.tcl
projects/address_module/block_design.tcl
projects/averager_module/averager.tcl
projects/averager_module/block_design.tcl
projects/base/block_design.tcl
projects/blink/main.yml
projects/oscillo/main.yml
projects/oscillo/oscillo.tcl
projects/peak_detector_module/block_design.tcl
projects/peak_detector_module/peak_detector.tcl
projects/pid/main.yml
projects/spectrum/main.yml
projects/spectrum/spectrum.tcl
projects/spectrum_module/block_design.tcl
projects/spectrum_module/spectrum.tcl
scripts/templates/config.tcl

* use namespaces for modules
* automatic calculation of cfg_size and sts_size

Clean modules

---

Makefile
boards/red-pitaya/base_system.tcl
boards/red-pitaya/config/ports.tcl
fpga/tcl/config_register.tcl
fpga/tcl/dac_controller.tcl
fpga/tcl/pid_controller.tcl
fpga/tcl/status_register.tcl
fpga/tcl/utilities.tcl
projects/address_module/address.tcl
projects/averager_module/averager.tcl
projects/peak_detector_module/peak_detector.tcl
projects/spectrum/noise_floor.tcl
projects/spectrum/spectrum.tcl
projects/spectrum_module/spectrum.tcl
scripts/make.py

add procedures :
* `get_and_pin`
* `get_not_pin`
* `get_nor_pin`
* `get_GE_pin`
* `get_GT_pin`
* `get_LE_pin`
* `get_LT_pin`
* `get_EQ_pin`
* `get_NE_pin`
* `get_concat_pin`

play with tcl

---

Makefile
drivers/gpio/__init__.py
drivers/gpio/gpio.hpp
tests/tests_gpio.py
tests/tests_oscillo.py

Add unit tests for GPIO driver

Tests gpio

---

drivers/laser/__init__.py
tests/tests_gpio.py
tests/tests_laser.py

Tests laser

---

drivers/eeprom/eeprom.hpp
tests/instrument_manager.py
tests/tests_common.py
tests/tests_device_memory.py
tests/tests_eeprom.py
tests/tests_instrument_manager.py

More tests

---

fpga/cores/pulse_generator_v1_0/core_config.tcl
fpga/cores/pulse_generator_v1_0/pulse_generator.v
fpga/cores/pulse_generator_v1_0/pulse_generator_tb.v

Simple core that generates periodic pulses with specified width and period.

Pulse generator

---

Makefile
drivers/common/__init__.py
fpga/cores/edge_detector_v1_0/edge_detector_tb.v
os/api/__init__.py
tests/instrument_manager.py
tests/tests_common.py
tests/tests_instrument_manager.py

Add some tests and clean Makefile

Server version

---

drivers/device_memory/__init__.py
drivers/device_memory/device_memory.hpp
drivers/lib/dev_mem.hpp
scripts/make.py
scripts/templates/addresses.hpp
tests/project_config.py
tests/tests_device_memory.py

Memory configuration retrieved from the instrument

Extend dev mem

---

Makefile
drivers/common/common.hpp
drivers/device_memory/device_memory.hpp
drivers/eeprom/eeprom.hpp
drivers/gpio/gpio.hpp
drivers/init/init.hpp
drivers/laser/laser.hpp
drivers/lib/dac_router.hpp
drivers/lib/dev_mem.cpp
drivers/lib/dev_mem.hpp
drivers/lib/fifo_reader.hpp
drivers/lib/memory_map.cpp
drivers/lib/memory_map.hpp
drivers/oscillo/oscillo.cpp
drivers/oscillo/oscillo.hpp
drivers/pid/pid.hpp
drivers/spectrum/__init__.py
drivers/spectrum/spectrum.cpp
drivers/spectrum/spectrum.hpp
drivers/speed_test/speed_test.cpp
drivers/speed_test/speed_test.hpp
drivers/spi/spi.hpp
drivers/xadc/xadc.cpp
drivers/xadc/xadc.hpp

* Use std::array in spectrum
* Add more support to read/write std::array in DevMem

Use std array

---

os/api/__init__.py
os/api/api.py
os/api/config.yml

Remove deprecated upload of instrument via AWS S3.

Clean flask app

---

instruments/decimator/README.md
instruments/decimator/block_design.tcl
instruments/decimator/config.yml
instruments/decimator/decimator.hpp
instruments/decimator/decimator.py
instruments/decimator/fir.py
instruments/decimator/ideal_fir.py
instruments/decimator/test.py
instruments/decimator/test_33220A.py

see https://www.koheron.com/blog/2016/10/03/decimator-cic-filter

add decimator instrument

---

os/scripts/ubuntu.sh

remove unmaintained wireless stuff in ubuntu.sh

---

Makefile
drivers/lib/context.hpp
drivers/lib/memory_map.hpp
scripts/make.py

Split context

---

instruments/adc_dac/test.py
instruments/decimator/test.py
instruments/pulse_generator/test.py

Fixes some problems with python 3 found by #385.

Python3 compatibility

---

examples/cluster/cluster.hpp

Log on SSH and run the following command in the console:
```
journalctl -u koheron-server.service -f
```

Add debugging example in cluster.hpp

---

examples/dual-dds/block_design.tcl
examples/dual-dds/config.yml
examples/dual-dds/dual_dds.hpp
examples/dual-dds/ports.tcl
examples/dual-dds/web/app.ts
examples/dual-dds/web/control.ts
examples/dual-dds/web/dual_dds.ts
examples/dual-dds/web/index.html
examples/dual-dds/xdc/clocks.xdc
examples/dual-dds/xdc/ports.xdc

Simple instrument with control of the frequencies of each Red Pitaya's DAC

add Dual DDS instrument

---

examples/test/tests.hpp
python/koheron/koheron.py
tests/tests.py
tests/tests.ts

Fix errors in koheron.py vector and string type checking.

Fix koheron py

---

os/api/__init__.py
os/www/index.html
os/www/instruments.ts
os/www/instruments_widget.ts

* Upload instrument
* Remove instrument

Instruments widget

---

examples/alpha250/adc-dac-dma/adc-dac-dma.hpp
examples/alpha250/adc-dac-dma/block_design.tcl
examples/alpha250/adc-dac-dma/config.yml
examples/alpha250/adc-dac-dma/test.py
fpga/cores/tlast_gen_v1_0/core_config.tcl
fpga/cores/tlast_gen_v1_0/tlast_gen.v

Example of using the DMA to stream ADC and DAC data simultaneously (uses Xilinx AXI DMA IP in scatter gather mode)

Alpha250 dma

---

boards/alpha250/board.mk
examples/alpha250/phase-noise-analyzer/block_design.tcl
examples/alpha250/phase-noise-analyzer/config.yml
examples/alpha250/phase-noise-analyzer/cores/axis_lfsr_v1_0/axis_lfsr.v
examples/alpha250/phase-noise-analyzer/cores/axis_lfsr_v1_0/core_config.tcl
examples/alpha250/phase-noise-analyzer/cores/boxcar_filter_v1_0/boxcar_filter.v
examples/alpha250/phase-noise-analyzer/cores/boxcar_filter_v1_0/boxcar_filter_tb.v
examples/alpha250/phase-noise-analyzer/cores/boxcar_filter_v1_0/core_config.tcl
examples/alpha250/phase-noise-analyzer/cores/phase_unwrapper_v1_0/core_config.tcl
examples/alpha250/phase-noise-analyzer/cores/phase_unwrapper_v1_0/phase_unwrapper.v
examples/alpha250/phase-noise-analyzer/cores/phase_unwrapper_v1_0/phase_unwrapper_tb.v
examples/alpha250/phase-noise-analyzer/dds.hpp
examples/alpha250/phase-noise-analyzer/dma.hpp
examples/alpha250/phase-noise-analyzer/fir.py
examples/alpha250/phase-noise-analyzer/tcl/cordic.tcl
examples/alpha250/phase-noise-analyzer/test.py
os/scripts/ubuntu-development.sh

10 MHz with 180° 1 kHz phase modulation with Keysight 33600A measured with Alpha250 (internal clock)

Phase noise analyzer

---

examples/red-pitaya/adc-dac-bram/client/client.mk
examples/red-pitaya/adc-dac-bram/client/driver.hpp
server/client/koheron-client.hpp
server/context/i2c_dev.hpp
server/context/memory_manager.hpp
server/context/memory_map.hpp
server/templates/drivers_table.hpp
server/templates/memory.hpp
server/templates/operations.hpp

Check against drivers definitions for call and recv types and raise a compile-time error if necessary.

Cpp client type checking

---

python/koheron/__init__.py
python/koheron/koheron.py

couple of useful changes to the koheron client to allow 
1. expose instrument_status
2. add support for int8/int16/unsigned char
would be nice if we can deploy them so that pip install gets a version that includes these.

exanding koheron client

---

boards/alpha250-4/drivers/clock-generator.hpp
examples/alpha250-4/adc-bram/test_phase_shift.py

- Add 240 MHz and 100 MHz clock configurations for ALPHA250-4

Alpha250 4 clkcfgs
